permalink: /:year/:month/:day/:title.html
paginate: 50
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: XXX
  email: XXX
  link: XXX
  weibo: XXX
  github: XXX

# 站点信息
title: XXX的博客 
description: XXX的博客
url: XXX
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: XXX
favicon: XXX

# google analytics 设置
ga:
  id: XXX
  url: XXX

# disqus 设置
disqus:
  shortname: XXX

# 主题设置，自动激活某个标签
active: 技术

# 中文本地化
locals:
  #tags: 标签
  #about: 关于
  newest: 最新文章
  #archive: 归档
  content: 目录
